config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tweets do
        member do
          post :retweet
          put "like", to: "tweets#like"
          put "dislike", to: "tweets#dislike"
        end
  end
  
  mount API::Base, at: "/"

  devise_for :users
  resources :tweets
  resources :users
  resources :users, only: [:show]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tweets#index"
  

  get '/tweets/hashtag/:name', to: "tweets#hashtags"
  get '/search', to: "tweets#index"
  

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    TIME_ZONE = "Santiago"
    
    has_and_belongs_to_many :tags
    belongs_to :user
    belongs_to :retweet, class_name: 'Tweet',  foreign_key: 'retweet_id',optional: true
    
    acts_as_votable

    paginates_per 25


    after_create do 

      hashtags = self.tweet.scan(/#\w+/)
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        self.tags << tag
      end

    end

    before_update do 
       self.tags.clear #we delete all and add again.
       hashtags = self.tweet.scan(/#\w+/)
       hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        self.tags << tag
      end
    end

    def time_since_publish
        start_date = self.created_at.in_time_zone(TIME_ZONE)
        time_now = Time.now.in_time_zone(TIME_ZONE)
    
        t = time_now - start_date
    
        if t < 59.minutes
          mins = (t / 1.minute).round
          mins == 1 ? "#{mins} minuto" : "#{mins} minutos"
        else
          hours = (t / 1.hour).round
          hours == 1 ? "#{hours} hora" : "#{hours} horas"
        end
      end   

   

end

app/controllers/api/v1/tweets.rb
module API
    module V1
      class Tweets < Grape::API
        include API::V1::Defaults
        MAXTWEET = 50
            resource :tweets do
              desc "Return all Tweets"
              get "" do
                Tweet.all.limit(MAXTWEET)
                
              end


            desc "Return a Tweet"
              params do
                requires :id, type: Integer, desc: "ID of the Tweet"
              end
              get ":id" do
                Tweet.where(id: permitted_params[:id]).first!
              end

            desc 'Create a Tweet Object'
            params do
              
                #requires :user_id, type: Integer, allow_blank: false
                requires :tweet, type: String, allow_blank: false
                optional :retweet_id ,type: Integer
            end
            post do
              tweet = Tweet.new(declared(params))
              tweet.user_id = @user.id
              tweet.save
              
              { tweet: tweet, message: 'Tweet Created Successfull'}
              
            end

            desc 'Update existing Tweet Object'
            params do
              requires :tweet, type: String, allow_blank: false
              
            end
            route_param :id do
              put do
                tweet = Tweet.find(params[:id])
                tweet.update(declared(params))
                { message: 'Tweet Updated..'}
              rescue ActiveRecord::RecordNotFound
                error!('record not found', 404)
              end
            end


            #in method delete will appear that the object is already deleted even if u are not the owner, but if u check its working correctly..
            #for delete send a json like this { "id": 306 }, and the id in url..
            desc 'Deletes existing movie object'
            params do
              requires :id, type: Integer
            end
              delete ':id' do
                tweet = Tweet.find(params[:id])
                    if tweet.user_id == @user.id
                      tweet.delete
                        { message: 'Tweet Deleted'}
                    else
                        { message: 'El tweet que se esta intentando eliminar no le pertenece'}
                  end
                  { message: 'Tweet Deleted'}
              rescue ActiveRecord::RecordNotFound
                  error!('Record not found', 404)
              end
        
          end
        end
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
 
  before_action :set_tweet, only: %i[ show edit update destroy retweet]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets or /tweets.json
  USERS_FOLLOW = 9

  def index
    @users = User.all.limit(USERS_FOLLOW)
    @tweet = Tweet.new
    @query = params[:query]
    if @query.nil?
      @tweets = Tweet.page params[:page]
    else
      @tweets = Tweet.where("tweets.tweet ILIKE ?",["%#{@query}%"]).page(params[:page])
      @users = User.where("users.name ILIKE ?",["%#{@query}%"]).page(params[:page])
    end
    
    
    @feed_items = current_user.feed.page params[:page] unless current_user.nil?
    @tagg = Tag.all
    
  end
  
  def hashtags
    
    @tag = Tag.find_by(name: params[:name])
    @tweets = @tag.tweets 
    @tweet = Tweet.new
    @tweeets = Tag.page params[:page]
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @user = User.find(params[:id])
    
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
    @retweet = Tweet.find(params["tweet_id"])
    if @retweet.nil?
      @tweet = current_user.tweets.new
    else
      @tweet = current_user.tweets.new
      @retweet.increment!(:retweet_count)

    end

  end

  def like
    @tweet = Tweet.find(params[:id])
    @tweet.liked_by current_user
    @tweet.increment!(:likes_count)
    redirect_to '/'
  end
  
  def dislike
    @tweet = Tweet.find(params[:id])
    @tweet.disliked_by current_user
    @tweet.decrement!(:likes_count)
    redirect_to '/'
  end

  # GET /tweets/1/edit
  def edit
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Tweet.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # POST /tweets or /tweets.json
  def create
   
    @tweet = current_user.tweets.new(tweet_params)
    
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    #if not @tweet.retweet_id.nil?
     # @tweet.decrement!(:retweet_count)
      #end
    @tweet.destroy
    
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end

  end


  def retweet
    
    tweet = current_user.tweets.new(retweet_id: @tweet.id)
     
    if tweet.save

      redirect_to root_path
        
    else
        redirect_to :back, alert: "unable to retweet"
    
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet, :retweet_id).merge(user: current_user)
    end

    

  

end

app/helpers/tweets_helper.rb
module TweetsHelper

    def render_with_hashtags(tweet)
        tweet.gsub(/#\w+/){|word| link_to word, "/tweets/hashtag/#{word.delete('#')}"}.html_safe
    end
end

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box"> 
        <figure class="media-left"> 
            <p class="image is-64x64"> 
                <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name)%>
            </p>
        </figure>
        <div class="media-content">
            <%= render 'tweets/form' %>
        </div>    
    </article>
    <%end%>

    
<% (@tweets.order(created_at: :desc)).each do | tweet | %>
    <div class="box"> 
        <article class="media"> 
            <div class="media-left">
                <figure class="image is-64x64">
                    <%=  gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name)%>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                   
                    <strong><%= tweet.user.name %> </strong><br />
                    <small><%= tweet.user.username %></small><br/>
                    <h6><%= tweet.tweet %> </p>
                     <% if tweet.retweet_id != nil  %>
                        <%= render 'retweet', tweet: tweet%>
                    <% end %>
        
                </div>
                <% if user_signed_in? %>
                <nav class="level">
                    <div class="level-left is-mobile"> 
                        <%= link_to tweet_path(tweet) do %>
                               <small> hace </small>
                             <%= tweet.time_since_publish %>
                        <% end %>

                        <%if tweet.user.email == current_user.email %>
                        <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                            <span class="icon"> 
                                <i class="fa fa-pencil" aria-hidden="true"></i>                             
                            </span>
                        <% end %>
                        <% else %>
                            <p class="is-hidden">u cant</p>
                        <%end %>
                        
                        <%if tweet.user.email == current_user.email %>
                                <%= link_to tweet, method: :delete, data: { confirm: "are you sure u want to delete this tweet?"} do %>
                                        <span class="icon"> 
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>                             
                                        </span>  
                                <%   end    %>
                        <% else %>
                                    <p class="is-hidden">u cant</p>
                        <%end%>
                        
                        
                            <% if user_signed_in? && tweet.user_id != current_user.id  %>
                                <div><%= link_to 'Retweet', new_tweet_path(tweet_id: tweet), class: "ml-2 mr-2" %></div>
                            <% end %>
                            <% if current_user.liked? tweet %>
                                <%= link_to dislike_tweet_path(tweet.id), method: :put do %>
                                <%= image_tag("like.png", :alt => "Like", height: 18, width: 20) %>
                                <%= tweet.get_likes.size %>
                            <% end %>
                            <% else %>
                                <%= link_to like_tweet_path(tweet), method: :put do %>
                                <%= image_tag("dislike.png", :alt => "Like", height: 18, width: 20) %>
                                <%= tweet.get_likes.size %>
                            <% end %>
                             
                        <% end %>
                    </div>
                </nav>
                 <% end %>
            </div>
        </article>
    </div>
<% end %>
<%= paginate @tweets%>
</div>


   

app/views/tweets/_feed2.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box"> 
        <figure class="media-left"> 
            <p class="image is-64x64"> 
                <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name)%>
            </p>
        </figure>
        <div class="media-content">
            
            <%= render 'tweets/form' %>
        </div>    
    </article>
    <%end%>

    
<% (@feed_items.order(created_at: :desc)).each do | tweet | %>
    <div class="box"> 
        <article class="media"> 
            <div class="media-left">
                <figure class="image is-64x64">
                    <%=  gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name)%>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                   
                    <strong><%= link_to tweet.user.name, tweet.user,  style: 'color:#33E9FF' %> </strong><br />
                    <small><%= tweet.user.username %></small><br/>
                    <h6><%= render_with_hashtags(tweet.tweet) %> </p>
                     <% if tweet.retweet_id != nil  %>
                        <%= render 'tweets/retweet', tweet: tweet%>
                    <% end %>
        
                </div>
                <% if user_signed_in? %>
                <nav class="level">
                    <div class="level-left is-mobile"> 
                        <%= link_to edit_tweet_path(tweet) do %>
                               <small> hace </small>
                             <%= tweet.time_since_publish %>
                        <% end %>

                        <%if tweet.user.email == current_user.email %>
                        <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                            <span class="icon"> 
                                <i class="fa fa-pencil" aria-hidden="true"></i>                             
                            </span>
                        <% end %>
                        <% else %>
                            <p class="is-hidden">u cant</p>
                        <%end %>
                        
                        <%if tweet.user.email == current_user.email %>
                                <%= link_to tweet, method: :delete, data: { confirm: "are you sure u want to delete this tweet?"} do %>
                                        <span class="icon"> 
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>                             
                                        </span>  
                                <%   end    %>
                        <% else %>
                                    <p class="is-hidden">u cant</p>
                        <%end%>
                        
                        
                            <% if user_signed_in? && tweet.user_id != current_user.id  %>
                                <%= link_to new_tweet_path(tweet_id: tweet), class: "ml-2 mr-2" do %>
                                    <span class="icon"> 
                                        <i class="fa fa-retweet" aria-hidden="true"></i>                             
                                    </span>
                                <% end %>
                            <% end %>
                            <% if current_user.liked? tweet %>
                                <%= link_to dislike_tweet_path(tweet.id), method: :put do %>
                                <%= image_tag("like.png", :alt => "Like", height: 18, width: 20) %>
                                <%= tweet.get_likes.size %>
                            <% end %>
                            <% else %>
                                <%= link_to like_tweet_path(tweet), method: :put do %>
                                <%= image_tag("dislike.png", :alt => "Like", height: 18, width: 20) %>
                                <%= tweet.get_likes.size %>
                            <% end %>
                             
                        <% end %>
                    </div>
                </nav>
                 <% end %>
            </div>
        </article>
    </div>
<% end %>
<%= paginate @tweets%>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :tweet, label: "Tweet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
    </div>
  </div>

  <%= f.button :submit, class: "button is-info" %>
  <% end %>

app/views/tweets/_form2.html.erb
<%= simple_form_for(@tweet) do |f| %>
    <%= f.error_notification %>
    <div class="field">
      <div class="control">
        <%= f.input :tweet, label: "Retweet about it", input_html:{ class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
        <%= f.hidden_field :retweet_id, value: @retweet.id%>
         <%= f.hidden_field :retweet_count, value: @tweet.increment!(:retweet_count)%>

          </div>
    </div>
    
    <%= f.button :submit , method: :post, class: "button is-info" %>
    <% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
   <nav class="panel">
        <p class="panel-heading"> Profile </p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                     <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name)%>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                       
                          <strong> <%= link_to current_user.name, current_user, style: 'color:#33E9FF'  %></strong><br />
                          <small><%= current_user.username%></small>                          
                       </p>
                    </div>
                </div>
            </article>
         </div> 
         <div class="panel-block">
                <div class="level is-mobile">
                    <div class="level-item has-centered-text">
                        <div>
                            <p class="heading">Tweets</p>
                            <p class="title is-6"><%= current_user.tweets.count %></p>
                        </div>                    
                    </div>
                    <div class="level-item has-centered-text">
                        <div>
                            <p class="heading">Following</p>
                            <%= current_user.following.count %>
                        </div>                    
                    </div>
                    <div class="level-item has-centered-text">
                        <div>
                            <p class="heading">Followers</p>
                            <%= current_user.followers.count %>
                        </div>                    
                    </div>
                </div>
         </div> 
   </nav>
</div>

app/views/tweets/_retweet.html.erb
<div class="box">
   <article class="media"> 
   <div class="media-left">
                <figure class="image is-64x64">
                    <%=  gravatar_image_tag(tweet.retweet.user.email, size: 64, alt: tweet.retweet.user.name)%>
                </figure>
            </div>
    <div class="media-content">
        <div class="content">
            <strong><%= tweet.retweet.user.name %> </strong><br />
            <small><%= tweet.retweet.tweet %> </small><br />
        </div>
    </div>
    </article>
</div>

app/views/tweets/_trends.html.erb
<div class="column ">
    <nav class="panel">
        <p class="panel-heading">Trends</p>
        <% @tagg.each do |tag| %>
         <div class="panel-block is-active"> 
         <article class ="media">
            <div class="media-content">
                <p>
                    <strong>
                      <%= link_to "# #{tag.name}" , "/tweets/hashtag/#{tag.name}"%>  
                    
                    </strong>
                </p>
            </div>
         </article>
         </div>  
        <% end %>
    </nav>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
    <nav class="panel"> 
          <div class="panel-heading"> Who To Follow </div>  
    </nav>
  <% @users.each do |user| %>
            
                <div class="panel-block">
                    <article class="media"> 
                        <div class="media-left">
                            <figure class="image is-32x32">  
                            <img src="https://bulma.io/images/placeholders/64x64.png">
                            </figure>
                        </div>
                        <div class ="media-content"> 
                            <p>
                                <strong><%= link_to user.name, user %></strong>
                                <small><%= user.username%> </small>
                            </p>
                        </div>        
                    </article>
                </div>
          
 <% end %> 

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweeet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/hashtags.html.erb
<div class="column is-half">
<% if user_signed_in? %>
<article class="media box"> 
    <figure class="media-left"> 
        <p class="image is-64x64"> 
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name)%>
        </p>
    </figure>
    <div class="media-content">
        <%= render 'tweets/form' %>
    </div>    
</article>
<%end%>


<% (@tweets.order(created_at: :desc)).each do | tweet | %>
    <div class="box"> 
        <article class="media"> 
            <div class="media-left">
                <figure class="image is-64x64">
                    <%=  gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name)%>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                <!--  
                    <strong><%= link_to tweet.user.name, user_path(tweet.user.id) %> </strong><br /> -->
                    <strong> <%= link_to tweet.user.name, tweet.user,  style: 'color:#33E9FF' %></strong><br />
                    <small><%= tweet.user.username %></small><br/>
                    <h6><%= render_with_hashtags(tweet.tweet) %> </p>
                     <% if tweet.retweet_id != nil  %>
                        <%= render 'tweets/retweet', tweet: tweet%>
                    <% end %>
        
                </div>
                <% if user_signed_in? %>
                <nav class="level">
                    <div class="level-left is-mobile"> 
                        <%= link_to edit_tweet_path(tweet) do %>
                               <small> hace </small>
                             <%= tweet.time_since_publish %>
                        <% end %>

                        <%if tweet.user.email == current_user.email %>
                        <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                            <span class="icon"> 
                                <i class="fa fa-pencil" aria-hidden="true"></i>                             
                            </span>
                        <% end %>
                        <% else %>
                            <p class="is-hidden">u cant</p>
                        <%end %>
                        
                        <%if tweet.user.email == current_user.email %>
                                <%= link_to tweet, method: :delete, data: { confirm: "are you sure u want to delete this tweet?"} do %>
                                        <span class="icon"> 
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>                             
                                        </span>  
                                <%   end    %>
                        <% else %>
                                    <p class="is-hidden">u cant</p>
                        <%end%>
                        
                        
                            <% if user_signed_in? && tweet.user_id != current_user.id  %>
                                <%= link_to new_tweet_path(tweet_id: tweet), class: "ml-2 mr-2" do %>
                                    <span class="icon"> 
                                        <i class="fa fa-retweet" aria-hidden="true"></i>                             
                                    </span>
                                <% end %>
                            <% end %>
                            <% if current_user.liked? tweet %>
                                <%= link_to dislike_tweet_path(tweet.id), method: :put do %>
                                <%= image_tag("like.png", :alt => "Like", height: 18, width: 20) %>
                                <%= tweet.get_likes.size %>
                            <% end %>
                            <% else %>
                                <%= link_to like_tweet_path(tweet), method: :put do %>
                                <%= image_tag("dislike.png", :alt => "Like", height: 18, width: 20) %>
                                <%= tweet.get_likes.size %>
                            <% end %>
                             
                        <% end %>
                    </div>
                </nav>
                 <% end %>
            </div>
        </article>
    </div>
<% end %>

<%= paginate @tweeets%>
</div>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in? %>
        <%= render 'profile'%>
        
      
    <% else %>
      <%= render 'trends' %>
    <% end %>

      <%= render 'feed' %>
      

      <%= render 'who-to-follow' %>
      
      <% if user_signed_in? %>
        <%= render 'trends' %>
      <% end %>
     
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Retweet</h1>
					<%= render 'tweets/form2' %>


				<div class="box mt-5">
					<article class="media"> 
   				<div class="media-left">
                <figure class="image is-64x64">
                    <%=  gravatar_image_tag(@retweet.user.email, size: 64, alt: @retweet.user.name)%>
                </figure>
            	</div>
    			<div class="media-content">
        		<div class="content">
            	<strong><%= @retweet.user.name %> </strong><br />
            	<small><%= @retweet.tweet %> </small><br />
        </div>
    </div>
    </article>
				</div>	
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>